apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bmt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx  # Replace this with your actual frontend image
          env:
            - name: BACKEND_URL
              value: "http://backend.bmt-app.svc.cluster.local"
          ports:
            - containerPort: 80
