apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: bmt-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Internal access only
